name: ptl255
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip:
    - lightning==2.5.5
    - torchdata
    - pretty-midi==0.2.10
    - pandas
    - scikit-learn
    - scipy
    - transformers
    - Flask
    - Werkzeug
    - cyclonedx-bom
