name: pt29rocm
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.13
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/rocm6.4
    - torchvision==0.24
    - Flask
    - gdown
    - matplotlib
    - numpy
    - scikit_learn
    - torch
    - Werkzeug
    - cyclonedx-bom
    - pretty_midi
