name: tf220
dependencies:
  - python=3.12
  - pip:
    - Flask
    - gdown
    - imageio
    - keras
    - keras_nlp
    - matplotlib
    - numpy
    - pandas
    #- scikit_learn
    - tensorflow[and-cuda]==2.20.0
    - tensorflow_datasets
    - Werkzeug
    - cyclonedx-bom
    - pretty_midi
    #- cirq
    #- seaborn
    #- sympy
    #- tensorflow_quantum
